.\" Copyright (C) 2012 Isaac Schemm
.TH VERVE-FOCUS "1" "February 2012" "verve-search-launcher" "User Commands"
.SH NAME
verve-search-launcher \- Launch a URL, replacing + with %2B and space with +
.SH SYNOPSIS
.B verve-search-launcher
.SH DESCRIPTION
.PP
This command is used by xfce4-verve-plugin to launch a web search with
proper behavior for + characters and spaces.
.SH AUTHOR
Isaac Schemm <isaacschemm@gmail.com>

