.\" Copyright (C) 2006 Simon Huggins
.TH VERVE-FOCUS "1" "August 2006" "verve-focus" "User Commands"
.SH NAME
verve-focus \- Focus the xfce4-verve-plugin input area
.SH SYNOPSIS
.B verve-focus
.SH DESCRIPTION
.PP
Running this command focuses the xfce4-verve-plugin's input area from the
commandline.  It may be especially useful to bind to a menu item or a key
press while using the xfce4-verve-plugin.
.SH AUTHOR
verve-focus was written by Jannis Pohlmann <jannis@xfce.org>
.PP 
This manual page was written by Simon Huggins <huggie@earth.li> for the
Debian project and is free software; see the source for copying conditions.
